// Code generated by Wire. DO NOT EDIT.

//go:generate go run github.com/google/wire/cmd/wire
//+build !wireinject

package main

import (
	"github.com/streadway/amqp"
	"go.mongodb.org/mongo-driver/mongo"
	"pixstall-artwork/app/artwork/delivery/http"
	mongo2 "pixstall-artwork/app/artwork/repo/mongo"
	"pixstall-artwork/app/artwork/usecase"
	rabbitmq2 "pixstall-artwork/app/commission/delivery/rabbitmq"
	"pixstall-artwork/app/msg-broker/repo/rabbitmq"
)

// Injectors from wire.go:

func InitArtworkController(db *mongo.Database, conn *amqp.Connection) http.ArtworkController {
	repo := mongo2.NewMongoArtworkRepo(db)
	msg_brokerRepo := rabbitmq.NewRabbitMQMsgBrokerRepo(conn)
	useCase := usecase.NewArtworkUseCase(repo, msg_brokerRepo)
	artworkController := http.NewArtworkController(useCase)
	return artworkController
}

func InitCommissionMessageBroker(db *mongo.Database, conn *amqp.Connection) rabbitmq2.CommissionMessageBroker {
	repo := mongo2.NewMongoArtworkRepo(db)
	msg_brokerRepo := rabbitmq.NewRabbitMQMsgBrokerRepo(conn)
	useCase := usecase.NewArtworkUseCase(repo, msg_brokerRepo)
	commissionMessageBroker := rabbitmq2.NewCommissionMessageBroker(useCase, conn)
	return commissionMessageBroker
}
